name: Economy
on: push
permissions:
  pages: write

jobs:
  build:
    name: Docker build and push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      image_url: ${{ steps.setOutput.outputs.image_url }}
    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'gh-pages'
    - uses: suisei-cn/actions-download-file@v1.3.0
      id: downloadfile 
      name: Download the file
      with:
        url: "https://poe.ninja/api/data/itemoverview?league=Standard&type=UniqueJewel"
        target: expedition/
        filename: eco_Standard_UniqueJewel.json
    - name: test output
      id: whatever
      run: |
        cat expedition/eco_Standard_UniqueJewel.json
        ls .
        ls expedition
    - run: |
       date > generated.txt
       git config user.name github-actions
       git config user.email github-actions@github.com
       git add .
       git commit -m "generated"
    - uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
