name: Economy
on: push

env:
  LEAGUE: Sanctum
  
jobs:
  build:
    name: Update unique items economy files
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'gh-pages'
        
    - uses: suisei-cn/actions-download-file@v1.3.0
      id: standard_jewel 
      with:
        url: "https://poe.ninja/api/data/itemoverview?league=Standard&type=UniqueJewel"
        target: expedition/
        filename: eco_Standard_UniqueJewel.json
        
    - uses: suisei-cn/actions-download-file@v1.3.0
      id: league-jewel 
      with:
        url: "https://poe.ninja/api/data/itemoverview?league=${{ env.LEAGUE }}&type=UniqueJewel"
        target: expedition/
        filename: "eco_${{ env.LEAGUE }}_UniqueJewel.json"
        
    - run: |
       date > generated.txt
       git config user.name github-actions
       git config user.email github-actions@github.com
       git add .
       git commit -m "generated"
       git push
